server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: notification-service

aparadhkavach:
  environment: ${APP_ENV:local}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
  service:
    name: ${SERVICE_NAME:aparadhkavach-notification-service}
  traces:
    exporter: otlp
  metrics:
    exporter: otlp

logging:
  level:
    root: ${LOG_LEVEL:INFO}
