package dev.aparadhkavach.commons.error;

/** Six categories per ADR-020: VAL, AUTH, DOM, GRAPH, AI, SYS. */
public enum ErrorCode {
  VAL_INVALID_REQUEST,
  VAL_CONSTRAINT_VIOLATION,
  AUTH_UNAUTHORIZED,
  AUTH_FORBIDDEN,
  DOM_RESOURCE_NOT_FOUND,
  DOM_CONFLICT,
  GRAPH_TRAVERSAL_FAILED,
  AI_RESPONSE_VALIDATION_FAILED,
  SYS_INTERNAL_ERROR,
  SYS_EXTERNAL_SERVICE_UNAVAILABLE
}
